<form action="dodaj/Klienta" method="post" class="window">
    <table>
        <tr>
            <td>Imie:</td>
            <td><input type="text" name="imieK" size=10px></td>
        </tr>
        <tr>
            <td>Nazwisko:</td>
            <td><input type="text" name="nazwiskoK" size=10px></td>
        </tr>
        <tr>
            <td>Nr. Dowodu:</td>
            <td><input type="text" name="nDowodu" size=10px></td>
        </tr>
        <tr>
            <td>PESEL:</td>
            <td><input type="text" name="nPesel" size=10px></td>
        </tr>
        <tr>
            <td>Telefon:</td>
            <td><input type="text" name="nTelefonu" size=10px></td>
        </tr>
        <tr>
            <td>Miejscowość:</td>
            <td><input type="text" name="miejscowosc" size=10px></td>
        </tr>
        <tr>
            <td>Ulica:</td>
            <td><input type="text" name="ulica" size=10px></td>
        </tr>
        <tr>
            <td>Kod Pocztowy:</td>
            <td><input type="text" name="kodPocztowy" size=10px></td>
        </tr>
        <tr>
            <td>Nr. budynku:</td>
            <td><input type="text" name="nrBudynku" size=10px></td>
        </tr>
        <tr>
            <td>Nr. Mieszkania:</td>
            <td><input type="text" name="nrMieszkania" size=10px></td>
        </tr>
    </table>
    <br/>
    <input type="submit" value="DODAJ KLIENTA" />
</form>