<style>
    form{
        display: flex;
        flex-direction: column;
        align-items: center;
    }form label{
        margin-top:2vh;
    }
</style>

<fieldset class="window bottomFlames">
    <legend>Klienci</legend>
    <img src="<?php site_url() ?>/template/img/fillers/yahooweek.gif" alt="Yahoo week">
    <form action="dodaj/klienta" method="post">
        <label>
            Imie:
            <input type="text" name="imieK">
        </label>

        <label>
            Nazwisko:
            <input type="text" name="nazwiskoK">
        </label>

        <label>
            Nr. Dowodu:
            <input type="text" name="nDowodu">
        </label>

        <label>
            PESEL:
            <input type="text" name="nPesel">
        </label>

        <label>
            Telefon:
            <input type="text" name="nTelefonu">
        </label>

        <label>
            Miejscowość:
            <input type="text" name="miejscowosc">
        </label>

        <label>
            Ulica:
            <input type="text" name="ulica">
        </label>

        <label>
            Kod Pocztowy:
            <input type="text" name="kodPocztowy">
        </label>

        <label>
            Nr. budynku:
            <input type="text" name="nrBudynku">
        </label>

        <label>
        Nr. Mieszkania:
            <input type="text" name="nrMieszkania">
        </label>

        <input type="submit" value="DODAJ KLIENTA" />
    </form>
</fieldset>