<fieldset class="window bottomFlames">
    <legend>Przykładowe inputy:</legend>
    <button>Przycisk</button>
    <button disabled>Przycisk wyłączony</button>
    <h1 class="rainbow-animation defaultFont" sty>jakis tekst</h1>
    <a href="https://www.youtube.com/watch?v=dQw4w9WgXcQ">Nie wolno klikać</a>
    <select name="" id="">
        <option value="">Opcja 1</option>
        <option value="">Opcja 2</option>
    </select>
    <div class="bottomFlames">
        aaaaaaa
        apache_child_terminateaa <br>aaaaa
    </div>
</fieldset>
