<fieldset class="window bottomFlames">
    <legend>Kontakt</legend>

    <p class="rainbow-animation">DVD-ZILLA</p><br>
    Biuro<br>
    774484703<br>
    biuro@dvdzilla.nysa.pl<br>
    Centrum Obsługi Kilenta<br>
    774484700<br>
    fax. 774352989<br>
    obslugaklienta@dvdzilla.nysa.pl<br>

    <form action="" method="post">
        <input type="email" name="email" placeholder="Twoj mail"><br>
        <textarea name="message" cols="30" rows="10" placeholder="Wiadomosc"></textarea>
        <img src="<?php site_url() ?>/template/img/fillers/emailme.gif" alt="Email me">
        <br>
        <input type="submit" value="WYSLIJ MAILA">
    </form>

    <img src="<?php site_url() ?>/template/img/fillers/mailkitten.gif" alt="KotMailowy">
</fieldset>