<fieldset class="window">
    <legend>Jakis tytul</legend>

    <form action="dodaj-rezysera" method="post">
        <table>
            <tr>
                <td>Imię:</td>
                <td><input type="text" name="imieR" size=10px></td>
            </tr>
            <tr>
                <td>Nazwisko:</td>
                <td><input type="text" name="nazwiskoR" size=10px></td>
            </tr>
        </table>
        <br/>
        <input type="submit" value="DODAJ REŻYSERA" />
    </form>

</fieldset>