<style>
    form{
        display: flex;
        flex-direction: row;
        justify-content: center;
        margin: 5%;
    }form legend{
        margin-right:2%;
    }
</style>

<fieldset class="window bottomFlames">
    <legend>Panel zarządzania</legend>

    <form action="dodaj/film" method="post">
        <legend>Dodawanie filmu</legend>
        <input type="submit" value="DODAJ FILM">
    </form>

    <hr>

    <form action="dodaj/film3" method="post">
        <legend>Dodawanie gatunków do filmów</legend>
        <input type="submit" value="DODAJ GATUNKI">
    </form>

    <hr>

    <form action="dodaj/egzemplarz" method="post">
        <legend>Dodawanie egzemplarzy</legend>
        <label>
            Wybór filmów:
            <?php
                $con = createConnection();
        
                $query = $con->query("SELECT ID, Tytul from film ORDER BY Tytul");
                $html = '<select name="film">';
                while($film = mysqli_fetch_array($query)){
                   $html .= '<option value="' . $film['ID']. '">' . $film['Tytul'] . '</option>';
                }
                $html .= '</select>';
                echo $html;
                $con->close();
            ?>
        </label>
        <input type="submit" value="DODAJ EGZEMPLARZ">
    </form>

    <hr>

    <form action="dodaj/rezysera" method="post">
        <legend>Dodawanie reżysera</legend>
        <label>
            Imię:
            <input type="text" name="imieR">
        </label>
        <label>
            Nazwisko:
            <input type="text" name="nazwiskoR">
        </label>
        <input type="submit" value="DODAJ REŻYSERA">
    </form>

    <hr>

    <form action="dodaj/wytwornie" method="post">
        <legend>Dodawanie wytwórni</legend>
        <label>
            Nazwa wytwórni:
            <input type="text" name="wytwornia">
        </label>
        <input type="submit" value="DODAJ WYTWÓRNIE">
    </form>

    <hr>

    <form action="dodaj/kategorie" method="post">
        <legend>Dodawanie kategorii</legend>
        <label>
            Kategoria:
            <input type="text" name="kategoria">
        </label>
        <input type="submit" value="DODAJ KATEGORIĘ">
    </form>

    <hr>

    <form action="dodaj/gatunek" method="post">
        <legend>Dodawanie gatunku</legend>
        <label>
            Nazwa gatunku:
            <input type="text" name="gatunek">
        </label>
        <input type="submit" value="DODAJ GATUNEK">
    </form>

</fieldset>