<fieldset class="window">
    <legend>Produkty</legend>
    <div class="spaceAround">
        <img src="<?php site_url() ?>/template/img/fillers/hot.gif" alt="Hot content!">
        <p>Wypozyczenia plyt: <img src="<?php site_url() ?>/template/img/fillers/counter.gif" alt="∞"></p>
    </div>
    <form action="" method="post">
        <select name="filter">
            <option value="available">Dostepne</option>
            <option value="all">Wszystkie</option>
        </select>
        <input type="submit" value="FILTRUJ">
    </form>

    
    <?php
        $con = createConnection();

        $query=$con->query(
            "SELECT * from egzemplarze inner join film on egzemplarze.`ID Filmu`=film.ID where egzemplarze.czyDostepny"
        );
        $html = '';
        while($film = mysqli_fetch_array($query)){
            $html .= ' ' . $film['ID']. ' ' . $film['Tytul'] . ' ';
         }

        //  $query = "SELECT * FROM wypozyczenia WHERE `ID Egzemplarza` IN (SELECT ID FROM egzemplarze WHERE CzyDostepny = 0 AND `ID Filmu` IN (SELECT ID FROM film WHERE Tytul IN (SELECT Tytul FROM film WHERE ID IN (SELECT `ID filmu` FROM egzemplarze WHERE ID = `ID Egzemplarza`))))";

        //  // Pobranie wyniku zapytania
        //  $result = $con->query($query);
         
        //  // Pętla przez wynik zapytania
        //  while ($row = $result->fetch_assoc()) {
        //      echo "<p>" . $row['ID Egzemplarza'] . " " . $row['ID Klienta'] . " " . $row['Data Wypozyczenia'] . "</p>";
        //  }

    ?>

</fieldset>