<fieldset class="window">
    <legend>Produkty</legend>
    <div class="spaceAround">
        <img src="<?php site_url() ?>/template/img/fillers/hot.gif" alt="Hot content!">
        <p>Wypozyczenia plyt: <img src="<?php site_url() ?>/template/img/fillers/counter.gif" alt="∞"></p>
    </div>
    <form action="" method="post">
        <select name="filter">
            <option value="available">Dostepne</option>
            <option value="all">Wszystkie</option>
            <option value="late">Spoznione</option>
        </select>
        <input type="submit" value="FILTRUJ">
    </form>

    
    <?php
        if(!isset($_POST['filter']))
            return;
        
        $con = createConnection();

        $query;

        switch($_POST['filter']){
            case 'available':
                $query = "SELECT film.Tytul, rezyser.Imie, rezyser.Nazwisko, wytwornia.`Nazwa Wytwornii` from egzemplarze ".
                "inner join film on egzemplarze.`ID Filmu`=film.ID ".
                "inner join rezyser on film.`ID Rezysera`=rezyser.ID ".
                "inner join wytwornia on film.`ID Wytworni`=wytwornia.ID ".
                "where egzemplarze.czyDostepny";
                break;
            case 'all':
                $query = "SELECT film.Tytul, rezyser.Imie, rezyser.Nazwisko, wytwornia.`Nazwa Wytwornii` from egzemplarze ".
                "inner join film on egzemplarze.`ID Filmu`=film.ID ".
                "inner join rezyser on film.`ID Rezysera`=rezyser.ID ".
                "inner join wytwornia on film.`ID Wytworni`=wytwornia.ID ";
                break;
            case 'late':
                $query = "SELECT film.Tytul, rezyser.Imie, rezyser.Nazwisko, wytwornia.`Nazwa Wytwornii` from egzemplarze ".
                "inner join film on egzemplarze.`ID Filmu`=film.ID ".
                "inner join rezyser on film.`ID Rezysera`=rezyser.ID ".
                "inner join wypozyczenia on wypozyczenia.`ID Egzemplarza`=egzemplarze.ID ".
                "inner join wytwornia on film.`ID Wytworni`=wytwornia.ID ".
                "where wypozyczenia.`Termin Oddania` < now() and ".
                "egzemplarze.czyDostepny=0";
                break;
        }
        $result = $con->query($query);

        $html = '';
        while($array = mysqli_fetch_array($result)){
            foreach($array as $key => $value){
                if(is_numeric($key))
                    $html .= ' '.$value;
            }
            $html .= '<br>';
        }
        echo $html;
        $con->close();
    ?>

</fieldset>