<style>
    form{
        display: flex;
        flex-direction: column;
        align-items: center;
    }form label{
        margin-top:2%;
    }
</style>

<fieldset class="window bottomFlames">
    <legend>Wypozyczenia</legend>

    <img src="<?php site_url() ?>/template/img/fillers/geocities.jpg" alt="Geocities">

    <form action="" method="post">
        <label>
            Podaj PESEL klienta:
            <input type="text" name="pesel">
        </label>
        <label>
            Wybierz film:
            <?php
                require_once 'includes/db.php';
                $con = createConnection();
        
                $query = $con->query("SELECT egzemplarze.ID, film.Tytul from egzemplarze inner join film on egzemplarze.`ID Filmu` = film.ID where egzemplarze.czyDostepny;");
                $html = '<select name="film">';
                while($film = mysqli_fetch_array($query)){
                   $html .= '<option value="' . $film['ID']. '">' . $film['Tytul'] . '</option>';
                }
                $html .= '</select>';
                echo $html;
                $con->close();
            ?>
        </label>
        <label>
            <p id="monthsLabel">Ilosc miesiecy: 1</p>
            <label for="monthsRange">Mniej</label>
            <input name="miesiace" id="monthsRange" type="range" min="1" max="5" value="1" oninput="showMonthsRangeValue(this.value)">
            <label for="monthsRange">Wiecej</label>
        </label>
        <input type="submit" value="DODAJ WYPOZYCZENIE">
    </form>
            
    <?php
        include_once 'includes/db.php';

        if(isset($_POST['pesel'], $_POST['miesiace'], $_POST['film'])){
            $pesel = $_POST['pesel'];
            $miesiace = $_POST['miesiace'];
            $idEgzemplarza = $_POST['film'];
            $cena = 30*$miesiace;
            $con=createConnection();

            $userQuery=$con->query("SELECT ID from klienci where PESEL=".w($pesel)." limit 1");
            if($userQuery!==false){
                $idKlienta = $userQuery->fetch_assoc()['ID'];
                $values=['null', $idKlienta, $cena, 'NOW()', 'DATE_ADD(NOW(), INTERVAL '.$miesiace.' MONTH)', $idEgzemplarza];

                $con->query("INSERT into wypozyczenia values(". join(', ', $values) .")");
                echo 'Wypozyczono egzemplarz';

                $con->query("UPDATE egzemplarze set czyDostepny=0 where ID=".$idEgzemplarza);
            }else
                echo 'Nie znaleziono klienta o peselu '.$pesel;
            $con->close();
        }
    ?>
</fieldset>

<script>
    function showMonthsRangeValue(value){
        document.querySelector("#monthsLabel").textContent='Ilosc miesiecy: '+value;
    }
</script>