<?php

    $id = $_POST['film'];
    $amount = $_POST['amount'];

    $con = createConnection();
    for($i=0;$i<$amount; $i++)
        $query = $con->query("INSERT into egzemplarze values(null, ".$id.", 1)");
    $con->close();

    header('Location: '.config('site_url').'/panel');
    exit();

?>
<fieldset class="window bottomFlames">
    <legend>Dodawanie Egzemplarza</legend>
    Dodano egzemplarz
</fieldset>