<?php
        $film = $_POST['film'];
        $gatunek = $_POST['gatunek'];

        $con =  createConnection();
        
        $query = $con -> query("INSERT into `gatunki pomocnicza` values(null, ".w($gatunek).", ".w($film).")");

        if($query == false)
                echo 'Nie dodano gatunku.';

        $con -> close();

        header('Location: '.config('site_url').'/dodaj/film3');
        exit();