<?php
        $tytul = $_POST['tytul'];
        $rezyser = $_POST['rezyser'];
        $wytwornia = $_POST['wytwornia'];
        $kategoria = $_POST['kategoria'];

        $con =  createConnection();
        
        $query = $con -> query("INSERT into `film` values(null, ".w($rezyser).", ".w($wytwornia).", ".w($kategoria).", ".w($tytul).")");

        if($query==false)
                echo 'Nie udalo sie dodać filmu.';

        $con -> close();

        header('Location: '.config('site_url').'/dodaj/film');
        exit();