<?php
    require_once 'includes/db.php';

    $imieK = $_POST["imieK"];
    $nazwiskoK = $_POST["nazwiskoK"];
    $nDowodu = $_POST["nDowodu"];
    $nPesel = $_POST["nPesel"];
    $nTelefonu = $_POST["nTelefonu"];
    $miejscowosc = $_POST["miejscowosc"];
    $ulica = $_POST["ulica"];
    $kodPocztowy = $_POST["kodPocztowy"];
    $nrBudynku = $_POST["nrBudynku"];
    $nrMieszkania = $_POST["nrMieszkania"];

    $con = createConnection();

    $checkingQuery = $con->query("SELECT * from adres where Miejscowosc=".w($miejscowosc).
        " AND Ulica=".w($ulica).
        " AND `Kod Pocztowy`=".w($kodPocztowy).
        " AND `Nr Budynku`=".$nrBudynku.
        " AND `Nr Mieszkania`=".$nrMieszkania.
        " LIMIT 1"
    );

    $addressId;
    if(mysqli_affected_rows($con) <= 0){
        $addressValues = ['null', w($miejscowosc), w($ulica), w($kodPocztowy), $nrBudynku, $nrMieszkania];
    
        $addressQuery = $con->query("INSERT into adres values(". join(', ', $addressValues) .")");
        $addressId = mysqli_insert_id($con);
    }else{
        $addressId = $checkingQuery->fetch_assoc()['ID'];
    }

    $values = ['null', w($imieK), w($nazwiskoK), w($nDowodu), w($nTelefonu), w($nPesel), $addressId];

    $query = $con->query("INSERT into klienci values(". join(', ', $values) .")");

    if(mysqli_affected_rows($con) != 1){
        echo 'Juz wystepuje ten klient';
    }

    $con->close();